spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
        spring.json.add.type.headers: false
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "nuts.commerce.orderservice.event"
        spring.json.value.default.type: "nuts.commerce.orderservice.event.inbound.OrderInboundEvent"
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: app
    password: app_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

system:
  outbox-publisher:
    enabled: true
    fixed-delay: 5000
    claim-batch-size: 50
    claim-locked-by: nuts-worker
    executor:
      core-pool-size: 4
      max-pool-size: 8
      queue-capacity: 500
      await-termination-seconds: 10

  order-event-listener:
    enabled: true
    topic: order-event
    group-id: order-service-group

kafka:
  reservation-event-producer:
    topic: reservation-event

  payment-event-producer:
    topic: payment-event

rest:
  product-service:
    base-url: http://localhost:8080
    product-snapshot-endpoint: /api/products/search/all
    api-key: dev-api-key-5678
server:
  port: 8083
