spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "nuts.commerce.productservice.event"
        spring.json.value.default.type: "nuts.commerce.productservice.event.inbound.ProductInboundEvent"


  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: app
    password: app_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      encoding: UTF-8
      data-locations: classpath:/data.sql


system:
  product-event-listener:
    enabled: true
    topic: product-inbound
    group-id: inventory-service-group-product

security:
  api:
    - key: prod-api-key-1234
      role: PROD
      principal: prod-client

    - key: dev-api-key-5678
      role: DEV
      principal: dev-client

server:
  port: 8080

logging:
  level:
    org.springframework.security: info