spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: app
    password: app_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

product:
  kafka:
    inbound:
      listener:
        enabled: true
      topic: product-inbound
      group-id: product-service-group
server:
  port: 8080
