spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
        spring.json.add.type.headers: false
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "nuts.commerce.inventoryservice.event"
        spring.json.value.default.type: "nuts.commerce.inventoryservice.event.inbound.ReservationInboundEvent"

  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: app
    password: app_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      encoding: UTF-8
      data-locations: classpath:/data.sql


system:
  startup-runner:
    enabled: true

  outbox-publisher:
    enabled: true
    fixed-delay: 5000
    claim-batch-size: 50
    claim-locked-by: nuts-worker
    executor:
      core-pool-size: 4
      max-pool-size: 8
      queue-capacity: 500
      await-termination-seconds: 10

  reservation-event-listener:
    enabled: true
    topic: reservation-event
    group-id: inventory-service-group-reservation

kafka:
  product-event-producer:
    topic: product-event

  reservation-event-producer:
    topic: order-event

server:
  port: 8081
