
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true


  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: app
    password: app_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update


inventory:
  kafka:
    inbound:
      listener:
        enabled: true
      topic: inventory-inbound
      group-id: inventory-service-group
    outbound:
      topic: inventory-outbound

  outbox:
    publisher:
      enabled: true
      fixed-delay: 5000
      executor:
        core-pool-size: 4
        max-pool-size: 8
        queue-capacity: 500
        await-termination-seconds: 10

server:
  port: 8081
